apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-eks
  template:
    metadata:
      labels:
        app: aws-eks
    spec:
      containers:
        - name: eks-registry
          image: 187386332334.dkr.ecr.ap-south-1.amazonaws.com/eks_registry:b4cc16ce35ed2b47a8dc1f65234d0a0f32a6e111
          imagepPullPolicy: always
          ports:
            - containerPort: 8080
