apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-eks
  template:
    metadata:
      labels:
        app: aws-eks
    spec:
      containers:
        - name: eks-registry
          image: 187386332334.dkr.ecr.ap-south-1.amazonaws.com/new:9dd96f62f33dca21a7e8fabcbf7eca14902d778b
          imagepPullPolicy: always
          ports:
            - containerPort: 8080
