apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-eks-app
  template:
    metadata:
      labels:
        app: aws-eks
    spec:
      containers:
        - name: eks-registry
          image: 187386332334.dkr.ecr.ap-south-1.amazonaws.com/eks_registry:30
          imagepPullPolicy: always
          ports:
            - containerport: 8080
