name: Express app on aws-eks

on:
  push:
    branches:
      - 'main'

jobs:
  push_and_deploy:
    name: push to aws-eks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: default
        id: install

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access }}
          aws-secret-key-id: ${{ secrets.aws_secret }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Docker meta tag
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #       images: vaishnaviwohlig/first
      #       tags: |
      #         type=raw,value={{date 'YYYYMMDDhhmmss'}}

      - name: Build and push
        env: 
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: eks-registry
          image_tag: 1.1
        run: | 
          docker build -t $registry/$repository:$image_tag .
          docker push $registry/$repository:$image_tag

      - name: update to kube config
        run: aws eks update-kubeconfig --name demos

      - name: deploy to eks
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
